sabnzbd:
  build: ./sabnzbd
  volumes:
    - ./sabnzbd/config/:/config/ # Also contains logs
    - ./storage/:/storage/ # Will download to this directory
  ports:
    - 8080
    - 9090

couchpotato:
  build: ./couchpotato
  volumes:
    - ./couchpotato/config/:/config/
    - ./storage/:/storage/ # Will download to this directory
  ports:
    - 5050
  links:
    - sabnzbd

sonarr:
  build: ./sonarr
  volumes:
    - ./sonarr/config/:/config/
    - ./storage/:/storage/
  ports:
    - 8989
  links:
    - sabnzbd
